---
title: "fig 3a and b"
output: html_document
---
```{r}
#explaination for the code for the fig3a and b
#1 run the full model for number of alien species in response to LU-type and 
#Lu-intensity interaction
#2 run the full model for alien proportion in response to LU-type and 
#Lu-intensity interaction
```

```{r setup, include=FALSE}
#install.packages("glmmTMB")
#install.packages("tidyverse")
#install.packages("data.table")
#install.packages("lme4")
#install.packages("ggplot2")
#install.packages("DHARMa")
#install.packages("multcomp")
library(glmmTMB)
library(tidyverse)
library(data.table)
library(lme4)
library(ggplot2)
library(DHARMa)
library(multcomp)
```
#1)import the data
```{r}
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
db$LU<-
  factor(db$LU,c("Primary","SV","Plantation","Pasture","Cropland","Urban"))
# reorder LU-intensity
db$LUI <- factor(db$LUI , levels = c("Minimal use" , "Light use" , "Intense use" , "Cannot decide"))
# remove observations with zero alien species
db <- subset(db , alien_freq > 0)
```
#2)alien number
```{r}
#run the statistical model
m <- glmer(alien_freq ~ LU*LUI + (1|SS/SSB) , data = db , family = poisson , 
           control = glmerControl(optimizer = "bobyqa" , 
                                  optCtrl = list(maxfun = 1e5)) , 
           nAGQ = 1 , subset = as.vector(db$LUI != "Cannot decide"))
# check overdispersion with DHARMa package
simulateResiduals(m , use.u = T) %>% testDispersion() # ok 
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB
# select fixed effects
m2 <- update(m , . ~ . -LU:LUI)
anova(m , m2) # keep interaction of LU-types and LU-intensity

# repeat for model with short database
 sds <- VarCorr(m) %>% as.data.frame()
 sd.total <- sqrt(sds[1 , 5]^2 + sds[2 , 5]^2)
 
#sue the cld to compare with each other
# predict only LU (i.e. averaged over LUI, possible since no interactions)
pred.full <- m %>% emmeans(specs = ~LU*LUI , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
levels(pred.full$LU)[1:2]<-c("Primary","Secondary")
# remove empty space
pred.full<-pred.full%>%drop_na()
names(pred.full)[3]<-c("num")
```

#2-1)fig.3a
```{r}
all.sp<-ggplot(pred.full , aes(LU , num,shape=LUI,color=LU))+
  geom_errorbar(aes(ymin = num-SE , ymax = num+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Number of alien species",
                     limits=c(0.5,4),breaks=seq(0,4,1))+
  geom_point(aes(shape=LUI),position = position_dodge(width=.6),size=3.5)+
  scale_shape_manual(name="LU-intensity",values=c(16, 17, 15))+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  guides(color=FALSE)+
  annotate(geom="text", x=0.818, y=1.45, label="a",size=4,color="#2166AC")+
  annotate(geom="text", x=1, y=2.1, label="bcd",size=4,color="#2166AC")+
  annotate(geom="text", x=1.2, y=2.7, label="bcd",size=4,color="#2166AC")+
  annotate(geom="text", x=1.82, y=2.7, label="b",size=4,color="#4393C3")+
  annotate(geom="text", x=2, y=2.55, label="bcd",size=4,color="#4393C3")+
  annotate(geom="text", x=2.2, y=2.4, label="abcd",size=4,color="#4393C3")+
  
  annotate(geom="text", x=2.82, y=3.15, label="bcd",size=4,color="#92C5DE")+
  annotate(geom="text", x=3, y=2.5, label="bcd",size=4,color="#92C5DE")+
  annotate(geom="text", x=3.2, y=1.8, label="abcd",size=4,color="#92C5DE")+ 
  annotate(geom="text", x=3.82, y=2.32, label="bcd",size=4,color="#F4A582")+
  annotate(geom="text", x=4, y=2.6, label="bc",size=4,color="#F4A582")+
  annotate(geom="text", x=4.2, y=2.5, label="abcd",size=4,color="#F4A582")+
  
  annotate(geom="text", x=4.82, y=2.7, label="bc",size=4,color="red")+
  annotate(geom="text", x=5, y=1.8, label="ad",size=4,color="red")+
  annotate(geom="text", x=5.2, y=2, label="acd",size=4,color="red")+
  annotate(geom="text", x=5.82, y=3, label="bcd",size=4,color="#B2182B")+ 
  annotate(geom="text", x=6, y=3.25, label="bcd",size=4,color="#B2182B")+ 
  annotate(geom="text", x=6.2, y=3.12, label="abcd",size=4,color="#B2182B")+  
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=12),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.5,0.94)) 
all.sp
#ggsave(all.sp,filename = '/xx/fig.3a.tiff',compression='lzw', width = 10,height = 3,dpi=200)
```
#2-2) for additive model
##fig.s3
```{r}
# predict additive model
m.add <- update(m , . ~ . -LU:LUI)
pred.add.LU <- m.add %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = F , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
pred.add.LU$predictor <- "LU-type"
#for LU-intensity
pred.add.LUI <- m.add %>% emmeans(specs = ~LUI , type = "response") %>%
  cld(bias.adj = F , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
pred.add.LUI$predictor <- "LU-intensity"
names(pred.add.LUI)[1] <- "LU"
#combined the rows
pred.add <- rbind(pred.add.LU , pred.add.LUI)
names(pred.add)[2]<-"num"
levels(pred.add$predictor)
levels(pred.add$LU)[1:2]<-c("Primary","Secondary")
#change factor
pred.add$predictor<-as.factor(pred.add$predictor)
pred.add$predictor<-factor(pred.add$predictor,c("LU-type","LU-intensity"))
# plot
all.sep<-ggplot(pred.add , aes(LU , num , group = predictor))+
  geom_errorbar(aes(ymin = num-SE , ymax = num+SE,width=0.3))+
    scale_y_continuous(name="Number of alien species",
                     limits=c(0,3),breaks=seq(0,3,1))+
  geom_point(size=3)+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        panel.grid.major.y = element_line(size = 0.1 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.title.x = element_blank(),
        legend.position = "bottom") + 
  geom_text(aes(label = .group, y = num+SE+0.2) ) + 
  facet_wrap(.~predictor , scales = "free_x")
all.sep
#ggsave(all.sep,filename = '/xx/num_all_sep.tiff',compression='lzw', width = 10,height = 4,dpi=200)
```

#3) alien proportion
#3-1)import the data
```{r}
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
db$LU<-
  factor(db$LU,c("Primary","SV","Plantation","Pasture","Cropland","Urban"))
# reorder LU-intensity
db$LUI <- factor(db$LUI , levels = c("Minimal use" , "Light use" , "Intense use" , "Cannot decide"))
# remove observations with zero alien species
db <- subset(db , alien_freq > 0)
# removing papers which have no aliens throughout all sites is unnecessary here, as per definition only studies including aliens are kept
# make proportion of aliens
db$alien_prop <- db$alien_freq / db$pred_freq
# alien proportion contains 1, therefore apply lemon squeezer following Smithson M, Verkuilen J (2006). "A Better Lemon Squeezer? Maximum-Likelihood Regression with Beta-Distributed Dependent Variables." Psychological Methods, 11 (1), 54-71
db$alien_prop_squeezed <- (db$alien_prop * (nrow(db)-1) + 0.5) / nrow(db)
```
#3-2)run the model
```{r}
m <- glmmTMB(alien_prop_squeezed ~ LU*LUI + (1|SS/SSB) , data = db[db$LUI != "Cannot decide" , ] , family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. 
simulateResiduals(m , use.u = T) %>% testDispersion() # seems OK 
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS
m<-m2
simulateResiduals(m , use.u = T) %>% testDispersion() # seems OK 

VarCorr(m)
# calculate combined effect for several random effects
sd.total <- sqrt(1.7201e+00 ^2+4.3675e-05^2)
# predict only LU (i.e. averaged over LUI, possible since no interactions)
pred.full.pro <- m %>% emmeans(specs = ~LU*LUI , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
names(pred.full.pro)[3]<-c("prob")
levels(pred.full.pro$LU)[1:2]<-c("Primary","Secondary")
```
#3-3)fig3b
```{r}
alien.p<-ggplot(pred.full.pro , aes(LU , prob,shape=LUI,color=LU))+
  geom_errorbar(aes(ymin = prob-SE , ymax = prob+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien proportions",
                     limits=c(0.25,0.6),breaks=seq(0.3,0.6,0.1))+
  geom_point(aes(shape=LUI),position = position_dodge(width=.6),size=3.5)+
  scale_shape_manual(name="LU-intensity",values=c(16, 17, 15))+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  guides(color=FALSE)+
  annotate(geom="text", x=0.818, y=0.4, label="a",size=4,color="#2166AC")+
  annotate(geom="text", x=1, y=0.44, label="ab",size=4,color="#2166AC")+
  annotate(geom="text", x=1.2, y=0.48, label="abc",size=4,color="#2166AC")+
  annotate(geom="text", x=1.82, y=0.43, label="ab",size=4,color="#4393C3")+
  annotate(geom="text", x=2, y=0.44, label="ab",size=4,color="#4393C3")+
  annotate(geom="text", x=2.2, y=0.48, label="abc",size=4,color="#4393C3")+
  
  annotate(geom="text", x=2.82, y=0.45, label="abc",size=4,color="#92C5DE")+
  annotate(geom="text", x=3, y=0.48, label="bc",size=4,color="#92C5DE")+
  annotate(geom="text", x=3.2, y=0.51, label="bc",size=4,color="#92C5DE")+ 
  annotate(geom="text", x=3.82, y=0.43, label="abc",size=4,color="#F4A582")+
  annotate(geom="text", x=4, y=0.45, label="abc",size=4,color="#F4A582")+
  annotate(geom="text", x=4.2, y=0.465, label="abc",size=4,color="#F4A582")+
  
  annotate(geom="text", x=4.818, y=0.51, label="c",size=4,color="red")+
  annotate(geom="text", x=5, y=0.45, label="abc",size=4,color="red")+
  annotate(geom="text", x=5.2, y=0.46, label="abc",size=4,color="red")+
  annotate(geom="text", x=5.82, y=0.48, label="bc",size=4,color="#B2182B")+ 
  annotate(geom="text", x=6, y=0.495, label="abc",size=4,color="#B2182B")+ 
  annotate(geom="text", x=6.2, y=0.53, label="abc",size=4,color="#B2182B")+  
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=12),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.5,0.94)) 
alien.p
ggsave(alien.p,filename = '/xx/fig3.b.tiff',compression='lzw', width = 10,height = 3,dpi=200)
```

#Fig.s4
```{r}
# predict additive model, without interaction
m.add <- update(m , . ~ . -LU:LUI)
#lu-types
pred.add.LU <- m.add %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = F , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
pred.add.LU$predictor <- "LU-type"
#lu-intensity
pred.add.LUI <- m.add %>% emmeans(specs = ~LUI , type = "response") %>%
  cld(bias.adj = F , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
pred.add.LUI$predictor <- "LU-intensity"
names(pred.add.LUI)[1] <- "LU"
#add the rows
pred.add <- rbind(pred.add.LU , pred.add.LUI)
names(pred.add)[2]<-"prop"
levels(pred.add$predictor)
levels(pred.add$LU)[1:2]<-c("Primary","Secondary")
pred.add$predictor<-as.factor(pred.add$predictor)
pred.add$predictor<-factor(pred.add$predictor,c("LU-type","LU-intensity"))
# plot the figure
all.sep<-ggplot(pred.add , aes(LU , prop , group = predictor))+
  geom_errorbar(aes(ymin = prop-SE , ymax = prop+SE,width=0.3))+
    scale_y_continuous(name="Alien proportions",
                     limits=c(0.1,0.5),breaks=seq(0.1,0.5,0.1))+
  geom_point(size=3)+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        panel.grid.major.y = element_line(size = 0.1 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.title.x = element_blank(),
        legend.position = "bottom") + 
  geom_text(aes(label = .group, y = prop+SE+0.03) ) + 
  facet_wrap(.~predictor , scales = "free_x")
all.sep
#ggsave(all.sep,filename = '/xx/num_all_sep.tiff',compression='lzw', width = 10,height = 4,dpi=200)
```

