---
title: "fig4 analysis"
output: html_document
---
```{r}
#explaination for the code for fig4a-d
#1 run the LU-type model for number of alien species aross all taxon.
#2 run the LU-type model for number of alien species for ants, birds, spiders and vascular plants separately.
#3 run the LU-type model for alien proportion across all taxon.
#4 run the LU-type model for each taxa separately.
```

```{r setup, include=FALSE}
#install.packages("glmmTMB")
#install.packages("tidyverse")
#install.packages("data.table")
#install.packages("lme4")
#install.packages("ggplot2")
#install.packages("DHARMa")
#install.packages("multcomp")
library(glmmTMB)
library(tidyverse)
library(data.table)
library(lme4)
library(ggplot2)
library(DHARMa)
library(multcomp)
```
#1. Alien number
#1.1)import the data
```{r}
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
db$LU<-
  factor(db$LU,c("Primary","SV","Plantation","Pasture","Cropland","Urban"))
# reorder LU-intensity
db$LUI <- factor(db$LUI , levels = c("Minimal use" , "Light use" , "Intense use" , "Cannot decide"))
# remove observations with zero alien species
db <- subset(db , alien_freq > 0)
```
#1.1.1 LU only for all
```{r}
m <- glmer(alien_freq ~ LU + (1|SS/SSB), data = db , family = poisson)
# check overdispersion with DHARMa package to decide if OLRE is needed.
simulateResiduals(m , use.u = T) %>% testDispersion() # good enough!
################
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB
# repeat for model with short database
 sds <- VarCorr(m) %>% as.data.frame()
 sd.total <- sqrt(sds[1 , 5]^2 + sds[2 , 5]^2)
#get the cld to back-transfer and compare with each other
pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(pred.full)[2]<-"prob"
levels(pred.full$LU)[1:2]<-c("Primary","Secondary")
```
##fig4a
```{r}
all.LU<-ggplot(pred.full , aes(LU , prob,color=LU))+
  geom_errorbar(aes(ymin = prob-SE , ymax = prob+SE) ,width=0.2, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Number of alien species",
                     limits=c(-0.2,6),breaks=seq(0,6,2))+
  geom_point(position = position_dodge(width=.6),size=2.8)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  annotate(geom="text", x=1, y=2, label="a",size=4,color="#2166AC")+
  annotate(geom="text", x=2, y=2.8, label="b",size=4,color="#4393C3")+
  annotate(geom="text", x=3, y=2.7, label="bc",size=4,color="#92C5DE")+
  annotate(geom="text", x=4, y=2.6, label="bc",size=4,color="#F4A582")+
  annotate(geom="text", x=5, y=2.3, label="c",size=4,color="red")+
  annotate(geom="text", x=6, y=3.2, label="bc",size=4,color="#B2182B")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=13),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.position = "none")
all.LU
ggsave(all.LU,filename = '/Users/daijunliu/Downloads/fig.4a.tiff',width = 4.5,height = 3,dpi = 200)
```
#1.2.1 LU for each taxa
##ants
```{r}
db.t<-db[db$taxa=="Ants",]
m <- glmer(alien_freq ~ LU + (1|SS/SSB), data = db.t , family = poisson)
# check overdispersion with DHARMa package to decide if OLRE is needed.
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # SS is more simple
m<-m2
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
# repeat for model with short database
sds <- VarCorr(m) %>% as.data.frame()
sd.total <- sqrt(sds[1 , 5]^2 )
ant.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(ant.pred.full)[2]<-"prob"
```
##birds
```{r}
db.t<-db[db$taxa=="Birds",]
m <- glmmTMB(alien_freq ~ LU + (1|SS/SSB) , data = db.t , family = compois)
simulateResiduals(m , use.u = T) %>% testDispersion() #  good
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # 
m<-m2
simulateResiduals(m , use.u = T) %>% testDispersion() #  good
VarCorr(m)
sd.total <- sqrt(0.54133^2)
bird.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(bird.pred.full)[2]<-"prob"
```
##mammals
```{r}
db.t<-db[db$taxa=="Mammals",]
dplyr::count(db.t,LU)
dplyr::count(db.t,alien_freq)
#delete cropland due to low samples
db.t<-db.t[db.t$LU!="Cropland",]
db.t<-db.t[db.t$LU!="Pasture",]
#has fit: see ?isSingular
m <- glmer(alien_freq ~ LU + (1|SS/SSB) , data = db.t , family = poisson , 
           control = glmerControl(optimizer = "bobyqa" , 
                                  optCtrl = list(maxfun = 1e5)) , nAGQ = 1)
simulateResiduals(m , use.u = T) %>% testDispersion() # not good 
m <- glmer(alien_freq ~ LU + (1|SSB) , data = db.t , family = poisson , 
           control = glmerControl(optimizer = "bobyqa" , 
                                  optCtrl = list(maxfun = 1e5)) , nAGQ = 1)
simulateResiduals(m , use.u = T) %>% testDispersion() # not good 

m <- glmmTMB(alien_freq ~ LU + (1|SS/SSB) , data = db.t , family = compois)
simulateResiduals(m , use.u = T) %>% testDispersion() #  good
```
##spiders
```{r}
db.t<-db[db$taxa=="Spiders",]
m <- glmmTMB(alien_freq ~ LU + (1|SS/SSB) , data = db.t , family = compois)
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep ss is more simple
m<-m2
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
VarCorr(m)
sd.total <- sqrt(0.19204^2)

spider.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
spider.pred.full$LU<-as.character(spider.pred.full$LU)
spider.pred.full[6,]<-c("Urban",NA,NA,NA,NA,NA,"a")
spider.pred.full$LU<-as.factor(spider.pred.full$LU)
names(spider.pred.full)[2]<-"prob"
spider.pred.full$prob<-as.numeric(spider.pred.full$prob)
spider.pred.full$SE<-as.numeric(spider.pred.full$SE)
```
##vascular plants
```{r}
db.t<-db[db$taxa=="Vascular plants",]
m <- glmer(alien_freq ~ LU + (1|SS/SSB) , data = db.t, family = poisson)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate 
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB

sds <- VarCorr(m) %>% as.data.frame()
sd.total <- sqrt(sds[1 , 5]^2 + sds[2 , 5]^2)

plant.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(plant.pred.full)[2]<-"prob"
```
#1.2.2 combine 5 taxa
```{r}
names(ant.pred.full);names(bird.pred.full);
names(spider.pred.full);names(plant.pred.full)
ant.pred.full$taxa<-"Ants";bird.pred.full$taxa<-"Birds"
spider.pred.full$taxa<-"Spiders";plant.pred.full$taxa<-"Vascular plants"

data.all<-do.call("rbind", list(ant.pred.full[,c(1:3,7:8)],bird.pred.full[,c(1:3,7:8)],
     spider.pred.full[,c(1:3,7:8)],plant.pred.full[,c(1:3,7:8)]))
data.all$LU<-as.character(data.all$LU)
data.all$LU<-as.factor(data.all$LU)
levels(data.all$LU)[4:5]<-c("Primary","Secondary")
data.all$LU<-factor(data.all$LU,c("Primary","Secondary","Plantation",
                                  "Pasture","Cropland","Urban"))
```
#1.2.3 fig.4b
```{r}
data.all$taxa<-as.factor(data.all$taxa)
all.taxa<-ggplot(data.all , aes(LU , prob,color=taxa,shape=taxa))+
  geom_errorbar(aes(ymin = prob-SE , ymax = prob+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Number of alien species",
                     limits=c(-0.2,6),breaks=seq(0,6,2))+
  geom_point(position = position_dodge(width=.6),size=3)+
  scale_shape_manual(name="Taxa",values=c(16,17,3,7), 
                     label=c('Ants','Birds','Spiders','Vascular plants'))+
  scale_color_manual(name='Taxa',
                     values = c("brown1","lightgoldenrod4","dodgerblue",
                                "magenta"),
                     label=c('Ants','Birds',
                             'Spiders','Vascular plants'))+
  annotate(geom="text", x=0.92, y=2.05, label="a",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=1.92, y=1.95, label="ab",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=2.92, y=2.15, label="ab",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=3.92, y=1.8, label="a",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=4.92, y=2.1, label="ab",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=5.92, y=2.55, label="b",size=4,color="lightgoldenrod4")+
  
  annotate(geom="text", x=1.08, y=1.55, label="a",size=4,color="dodgerblue")+
  annotate(geom="text", x=2.08, y=1.7, label="a",size=4,color="dodgerblue")+
  annotate(geom="text", x=3.08, y=1.7, label="ab",size=4,color="dodgerblue")+
  annotate(geom="text", x=4.08, y=2.45, label="b",size=4,color="dodgerblue")+
  annotate(geom="text", x=5.08, y=1.7, label="ab",size=4,color="dodgerblue")+
  
  annotate(geom="text", x=1.23, y=2.15, label="a",size=4,color="magenta")+
  annotate(geom="text", x=2.23, y=3.75, label="b",size=4,color="magenta")+
  annotate(geom="text", x=3.23, y=3.75, label="bc",size=4,color="magenta")+
  annotate(geom="text", x=4.23, y=2.9, label="bc",size=4,color="magenta")+
  annotate(geom="text", x=5.23, y=2.8, label="c",size=4,color="magenta")+
  annotate(geom="text", x=6.23, y=5.45, label="bc",size=4,color="magenta")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.45,0.92)) 
all.taxa
ggsave(all.taxa,filename = '/Users/daijunliu/Downloads/all.taxa.tiff',width = 6.5,height = 3,dpi = 200)
```
#2. alien proportion
#2.1)import data
```{r}
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
db$LU<-
  factor(db$LU,c("Primary","SV","Plantation","Pasture","Cropland","Urban"))
# reorder LU-intensity
db$LUI <- factor(db$LUI , levels = c("Minimal use" , "Light use" , "Intense use" , "Cannot decide"))
# remove observations with zero alien species
db <- subset(db , alien_freq > 0)
# removing papers which have no aliens throughout all sites is unnecessary here, as per definition only studies including aliens are kept
# make proportion of aliens
db$alien_prop <- db$alien_freq / db$pred_freq
# alien proportion contains 1, therefore apply lemon squeezer following Smithson M, Verkuilen J (2006). "A Better Lemon Squeezer? Maximum-Likelihood Regression with Beta-Distributed Dependent Variables." Psychological Methods, 11 (1), 54-71
db$alien_prop_squeezed <- (db$alien_prop * (nrow(db)-1) + 0.5) / nrow(db)
```
#2.1.1 LU only for all
```{r}
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() #  OK enough!
################
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep it SS/SSB
m<-m2
simulateResiduals(m , use.u = T) %>% testDispersion() #  OK enough!
VarCorr(m)
sd.total <- sqrt(1.7288 ^2)
pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% 
  as.data.frame()
names(pred.full)[2]<-"prob"
levels(pred.full$LU)[2]<-"Secondary"
```
##fig.4c
```{r}
all<-ggplot(pred.full , aes(LU , prob,color=LU))+
  geom_errorbar(aes(ymin = prob-SE , ymax = prob+SE) ,width=0.2, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien proportions",
                     limits=c(0,1),breaks=seq(0,0.9,0.3))+
  geom_point(position = position_dodge(width=.6),size=2.8)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  annotate(geom="text", x=1, y=0.44, label="a",size=4,color="#2166AC")+
  annotate(geom="text", x=2, y=0.47, label="b",size=4,color="#4393C3")+
  annotate(geom="text", x=3, y=0.5, label="bc",size=4,color="#92C5DE")+
  annotate(geom="text", x=4, y=0.46, label="abc",size=4,color="#F4A582")+
  annotate(geom="text", x=5, y=0.5, label="c",size=4,color="red")+
  annotate(geom="text", x=6, y=0.52, label="bc",size=4,color="#B2182B")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=13),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.position = "none")
all
ggsave(all,filename = '/Users/daijunliu/Downloads/fig.4c.tiff',width = 4.5,height = 3,dpi = 200)
```

#2.2.1 LU for each taxa
##ants
```{r}
db.t<-db[db$taxa=="Ants",]
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db.t, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # slightly 
################
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # #ss is better
m <- m2
simulateResiduals(m , use.u = T) %>% testDispersion() # slightly 
VarCorr(m)
sd.total <- sqrt(1.4079  ^2)
ant.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(ant.pred.full)[2]<-"prob"
```
##birds
```{r}
db.t<-db[db$taxa=="Birds",]
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db.t, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. 
simulateResiduals(m , use.u = T) %>% testDispersion() #but seems OK enough!
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # ss/ssb/
VarCorr(m)
sd.total <- sqrt(0.14095 ^2+0.95297^2)
bird.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(bird.pred.full)[2]<-"prob"
```
##mammals
```{r}
db.t<-db[db$taxa=="Mammals",]
db.t<-db.t[db.t$LU!="Cropland",]
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db.t, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() #  OK enough!
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # remove block (both models very similar, therefore keep the simpler one)
m <- m2
simulateResiduals(m , use.u = T) %>% testDispersion() #  OK 
VarCorr(m)
sd.total <- sqrt(1.0719 ^2)

mam.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
mam.pred.full$LU<-as.character(mam.pred.full$LU)
mam.pred.full[5,]<-c("Cropland",NA,NA,NA,NA,NA,"a")
mam.pred.full[6,]<-c("Urban",NA,NA,NA,NA,NA,"a")
mam.pred.full$LU<-as.factor(mam.pred.full$LU)
names(mam.pred.full)[2]<-"prob"
mam.pred.full$prob<-as.numeric(mam.pred.full$prob)
mam.pred.full$SE<-as.numeric(mam.pred.full$SE)
levels(mam.pred.full$LU)
mam.pred.full$LU<-
  factor(mam.pred.full$LU,c("Primary","SV","Plantation", 
                      "Pasture","Cropland", "Urban"))
```
## spider
```{r}
db.t<-db[db$taxa=="Spiders",]
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db.t, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # good
################
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # remove block (both models very similar, therefore keep the simpler one)
m <- m2
simulateResiduals(m , use.u = T) %>% testDispersion() # good
VarCorr(m)
# calculate combined effect for several random effects
# sd.total <- sqrt(sds[1 , 5]^2)
sd.total <- sqrt(0.38171^2)

spider.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
spider.pred.full$LU<-as.character(spider.pred.full$LU)
spider.pred.full[6,]<-c("Urban",NA,NA,NA,NA,NA,"a")
spider.pred.full$LU<-as.factor(spider.pred.full$LU)
names(spider.pred.full)[2]<-"prob"
spider.pred.full$prob<-as.numeric(spider.pred.full$prob)
spider.pred.full$SE<-as.numeric(spider.pred.full$SE)
```
##vascular plants
```{r}
db.t<-db[db$taxa=="Vascular plants",]
m <- glmmTMB(alien_prop_squeezed ~ LU + (1|SS/SSB) , data = db.t, family = beta_family)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # good
################
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # remove block (both models very similar, therefore keep the simpler one)

VarCorr(m) 
sd.total <- sqrt(0.27314^2+1.26225^2)

plant.pred.full <- m %>% emmeans(specs = ~LU , type = "response") %>%
  cld(bias.adj = T , sigma = sd.total , sort = F , adjust = "bonferroni" , Letters = letters) %>% as.data.frame()
names(plant.pred.full)[2]<-"prob"
```

#2.2.2 combine
```{r}
names(ant.pred.full);names(bird.pred.full);names(mam.pred.full)
names(spider.pred.full);names(plant.pred.full)
ant.pred.full$taxa<-"Ants";bird.pred.full$taxa<-"Birds"
mam.pred.full$taxa<-"Mammals";spider.pred.full$taxa<-"Spiders"
plant.pred.full$taxa<-"Vascular plants"

data.all<-do.call("rbind", list(ant.pred.full[,c(1:3,7:8)],bird.pred.full[,c(1:3,7:8)],
     mam.pred.full[,c(1:3,7:8)],spider.pred.full[,c(1:3,7:8)],
     plant.pred.full[,c(1:3,7:8)]))
data.all$LU<-as.character(data.all$LU)

data.all$LU<-as.factor(data.all$LU)
levels(data.all$LU)[4:5]<-c("Primary","Secondary")
data.all$LU<-factor(data.all$LU,c("Primary","Secondary","Plantation",
                                  "Pasture","Cropland","Urban"))
```
#2.2.3 fig.4d
```{r}
data.all$taxa<-as.factor(data.all$taxa)
all.taxa<-ggplot(data.all , aes(LU , prob,color=taxa,shape=taxa))+
  geom_errorbar(aes(ymin = prob-SE , ymax = prob+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien proportion",
                     limits=c(0,1),breaks=seq(0,0.9,0.3))+
  geom_point(position = position_dodge(width=.6),size=3)+
    scale_shape_manual(name="Taxa",values=c(16,17,15,3,7), 
                     label=c('Ants','Birds',"Mammals",'Spiders','Vascular plants'))+
  scale_color_manual(name='Taxa',
                     values = c("brown1","lightgoldenrod4","cyan2","dodgerblue",
                                "magenta"),
                     label=c('Ants','Birds',"Mammals",
                             'Spiders','Vascular plants'))+
 
  annotate(geom="text", x=0.77, y=0.54, label="a",size=4,color="brown1")+
  annotate(geom="text", x=1.77, y=0.50, label="a",size=4,color="brown1")+
  annotate(geom="text", x=2.78, y=0.80, label="b",size=4,color="brown1")+
  annotate(geom="text", x=3.775, y=0.54, label="a",size=4,color="brown1")+
  annotate(geom="text", x=4.775, y=0.6, label="ab",size=4,color="brown1")+
  annotate(geom="text", x=5.775, y=0.62, label="ab",size=4,color="brown1")+ 
  
  annotate(geom="text", x=0.89, y=0.25, label="abc",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=1.89, y=0.21, label="a",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=2.89, y=0.235, label="ab",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=3.89, y=0.22, label="abc",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=4.89, y=0.27, label="c",size=4,color="lightgoldenrod4")+
  annotate(geom="text", x=5.89, y=0.29, label="bc",size=4,color="lightgoldenrod4")+

  annotate(geom="text", x=1.25, y=0.26, label="a",size=4,color="magenta")+
  annotate(geom="text", x=2.25, y=0.3, label="b",size=4,color="magenta")+
  annotate(geom="text", x=3.25, y=0.31, label="b",size=4,color="magenta")+
  annotate(geom="text", x=4.25, y=0.29, label="ab",size=4,color="magenta")+
  annotate(geom="text", x=5.25, y=0.33, label="b",size=4,color="magenta")+
  annotate(geom="text", x=6.25, y=0.48, label="c",size=4,color="magenta")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.45,0.93)) 
all.taxa
ggsave(all.taxa,filename = '/Users/daijunliu/Downloads/all.taxa.tiff',width = 6.5,height = 3,dpi = 200)
```

