---
title: "fig2 R code"
output: html_document
---
```{r}
#explaination for the code for the fig2 a-g
#1 import the package and library
#2-1 run the full model for the LU-types and LU-intensity interaction
#2-2 run the model of LU-type and LU-intensity separately in the additive model
#3 run the  the LU-type only model across all and for each taxa separately.

```
#1)Install the package
```{r setup, include=FALSE}
#install the packages and library
#install.packages("lme4")
#install.packages("emmeans")
#install.packages("tidyverse")
#install.packages("data.table")
#install.packages("lme4")
#install.packages("ggplot2")
#install.packages("DHARMa")
library(lme4)
library(data.table)
library(emmeans)
library(multcomp)
library(lme4)
library(ggplot2)
library(tidyverse)
library(DHARMa)
```
#2)import data
```{r}
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
#the alien ratio is wrong
db$alien_all<-with(db,alien_freq/pred_freq)
levels(as.factor(db$LU))
db$LU<-
  factor(db$LU,c("Primary","SV","Plantation","Pasture","Cropland","Urban"))
levels(as.factor(db$LUI))
db$LUI<-
  factor(db$LUI,c("Cannot decide","Minimal use","Light use","Intense use"))
# Alien presence/absence for logistical model. 
db$Alien.presence <- as.logical(db$alien_freq)
```
#3.1 run full model
```{r}
#delte the Urban under intense use due to lower samples
db.full.test <- subset(db,!(LU %in% "Urban" & LUI %in%"Intense use"))
#1change the refernce for LU-types to get the odds ratios compared to primary.
levels(db.full.test$LU)
db.full.test$LU = factor(db.full.test$LU, levels=c("Primary","SV","Plantation","Cropland","Pasture","Urban"))
db.full.test$LU = factor(db.full.test$LU, levels=c("Pasture","Urban","Cropland", "Plantation","SV", "Primary"))
#2 change the refernce for LU-intensity to get the odds ratios compared to minimal use.
levels(db.full.test$LUI)
db.full.test$LUI = factor(db.full.test$LUI, levels=c("Cannot decide","Minimal use","Light use","Intense use"))
db.full.test$LUI = factor(db.full.test$LUI, levels=c("Intense use", "Light use","Minimal use","Cannot decide"))
#3 run the models
m <- glmer(Alien.presence ~ LU*LUI + (1|SS/SSB) , 
          data = db.full.test , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1 , subset = as.vector(db.full.test$LUI != "Cannot decide"))

#4 check overdispersion
simulateResiduals(m , use.u = T) %>% testDispersion() # looks good
#5 select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # AIC is lower in full model(m)
#6 check whether keep the interaction of LU-types and LU-intensity
m2 <- update(m , . ~ . -LU:LUI)
anova(m , m2) # lower AIC to Keep interaction 
```
#3.2 get the odds ratios

```{r}
#1use emmeans to get the odds ratios
pred.full<-m %>% emmeans(specs = ~LU+LUI , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#2selelct the rows with odds ratios that compared to primary
data.2<-pred.full[grepl("Primary Minimal use",pred.full$contrast),]
data.2$contrast<-as.character(data.2$contrast)
#3add the reference level is 1.
data.2[18,]<-c("Primary Minimal / Primary Minimal use",1, NA,NA,NA,NA,NA,NA,NA)
library(stringr)
data.2[c('name1', 'name2')] <- str_split_fixed(data.2$contrast, '/', 2)
data.2[c('LU', 'LUI',"Use")] <- str_split_fixed(data.2$name1, ' ', 3)
data.2$LUI<-paste(data.2$LUI,data.2$Use)
names(data.2)
#4select the columns
data.3<-data.2[,c(1:9,12,13)]
data.3$LUI<-as.factor(data.3$LUI)
#5 set the factors
levels(data.3$LUI)[1:4]<-c("Intense use","Light use","Minimal use","Minimal use")
data.3$LU<-as.factor(data.3$LU)
levels(data.3$LU)[4:5]<-c("Primary","Secondary")
#6set the factor for LU-types/intensity
data.3$LU = factor(data.3$LU, levels=c("Primary","Secondary",
                                       "Plantation","Pasture","Cropland","Urban"))
data.3$LUI = factor(data.3$LUI, levels=c("Minimal use","Light use","Intense use"))
```
#3.3 make fig2a
```{r}
names(data.3)
data.3$odds.ratio<-as.numeric(data.3$odds.ratio)
data.3$SE<-as.numeric(data.3$SE)
all<-ggplot(data.3 , aes(LU , odds.ratio,shape=LUI,color=LU))+
  geom_errorbar(aes(ymin = odds.ratio-SE , ymax = odds.ratio+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Odds ratio of alien occurrence",
                     limits=c(0,48),breaks=seq(0,45,15))+
  geom_point(aes(shape=LUI),position = position_dodge(width=.6),size=3.5)+
  scale_shape_manual(name="LU-intensity",values=c(16, 17, 15))+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  guides(color=FALSE)+
  annotate(geom="text", x=1.2, y=7, label="*",size=7,color="#2166AC")+
  annotate(geom="text", x=1.81, y=7.5, label="***",size=7,color="#4393C3")+
  annotate(geom="text", x=2.2, y=10, label="***",size=7,color="#4393C3")+
  annotate(geom="text", x=2.81, y=11, label="**",size=7,color="#92C5DE")+
  annotate(geom="text", x=3, y=17, label="***",size=7,color="#92C5DE")+
  annotate(geom="text", x=3.22, y=11, label="***",size=7,color="#92C5DE")+ 
  
  annotate(geom="text", x=3.81, y=21, label="**",size=7,color="#F4A582")+
  annotate(geom="text", x=4, y=10, label="***",size=7,color="#F4A582")+
  annotate(geom="text", x=4.2, y=15, label="***",size=7,color="#F4A582")+
  
  annotate(geom="text", x=4.81, y=15, label="***",size=7,color="red")+
  annotate(geom="text", x=5.2, y=46, label="***",size=7,color="red")+
  annotate(geom="text", x=5.81, y=16, label="***",size=7,color="#B2182B")+ 
  annotate(geom="text", x=6, y=21, label="***",size=7,color="#B2182B")+ 
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.4,0.9)) 

all
ggsave(all,filename = '/xx/fig2.a.tiff',compression='lzw', width = 10,height = 3.2,dpi=200)
```

#3.4.1 fig.s2 LU-types
```{r}
#1check the LU-types and LU-intensity separately 
levels(db$LU)
db$LU = factor(db$LU, levels=c("Primary","SV","Plantation","Cropland","Pasture","Urban"))
db$LU = factor(db$LU, levels=c("Pasture","Urban","Cropland", "Plantation","SV", "Primary"))
db$LUI = factor(db$LUI, levels=c("Cannot decide","Minimal use","Light use","Intense use"))
db$LUI = factor(db$LUI, levels=c("Intense use", "Light use","Minimal use","Cannot decide"))
#2run the statistical model
m <- glmer(Alien.presence ~ LU+LUI + (1|SS/SSB) , 
          data = db , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1 , subset = as.vector(db$LUI != "Cannot decide"))
#3get the odds ratios by LU-types
pred.full_x<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
pred.full_x1<-pred.full_x[c(5,9,12,14,15),]
pred.full_x1$contrast<-as.character(pred.full_x1$contrast)
#4add the reference
pred.full_x1[6,]<-c("Primary",1, NA,NA,NA,NA,NA,NA,NA)
#5 change it as factor
pred.full_x1$contrast<-as.factor(pred.full_x1$contrast)
levels(pred.full_x1$contrast)<-c("Cropland","Pasture","Plantation",
                                "Primary","Secondary","Urban")
pred.full_x1$contrast = factor(pred.full_x1$contrast, levels=c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(pred.full_x1)[1]<-"LU"
#6change them as numberic
pred.full_x1$SE<-as.numeric(pred.full_x1$SE)
pred.full_x1$odds.ratio<-as.numeric(pred.full_x1$odds.ratio)
#7make graphy fig s2
LU.sep<-ggplot(pred.full_x1 , aes(LU , odds.ratio))+
  geom_errorbar(aes(ymin = odds.ratio-SE , ymax = odds.ratio+SE,width=0.3))+
    scale_y_continuous(name="Odds ratio of alien ocurrence",
                     limits=c(0,15),breaks=seq(0,15,5))+
  geom_point(size=3)+
  annotate(geom="text", x=0.7, y=15, label="a",size=6,color="black")+
  annotate(geom="text", x=2, y=4.5, label="***",size=6,color="black")+
  annotate(geom="text", x=3, y=8, label="***",size=6,color="black")+
  annotate(geom="text", x=4, y=8, label="***",size=6,color="black")+
  annotate(geom="text", x=5, y=8, label="***",size=6,color="black")+
  annotate(geom="text", x=6, y=13, label="***",size=6,color="black")+  
  
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=12),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.5,0.9))
LU.sep
#ggsave(all.sep,filename = '/xx/all_LU_sep.tiff',compression='lzw', width = 8,height = 4,dpi=200)
```
#3.4.2 fig.s2 LU-intensity
```{r}
#2 for LUI data
pred.full_y<-m %>% emmeans(specs = ~LUI , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
pred.full_y1<-pred.full_y[c(2,3),]
pred.full_y1$contrast<-as.character(pred.full_y1$contrast)
pred.full_y1[3,]<-c("Minimal use",1, NA,NA,NA,NA,NA,NA,NA)
pred.full_y1$contrast<-as.factor(pred.full_y1$contrast)
levels(pred.full_y1$contrast)<-c("Intense use","Light use","Minimal use")
pred.full_y1$contrast = factor(pred.full_y1$contrast, levels=c("Minimal use","Light use","Intense use"))
names(pred.full_y1)[1]<-"LU"
pred.full_y1$SE<-as.numeric(pred.full_y1$SE)
pred.full_y1$odds.ratio<-as.numeric(pred.full_y1$odds.ratio)

LUI.sep<-ggplot(pred.full_y1 , aes(LU , odds.ratio))+
  geom_errorbar(aes(ymin = odds.ratio-SE , ymax = odds.ratio+SE,width=0.3))+
    scale_y_continuous(name="Odds ratio of alien ocurrence",
                     limits=c(0,3),breaks=seq(0,3,1))+
  geom_point(size=3)+
  annotate(geom="text", x=0.6, y=3, label="b",size=6,color="black")+
  annotate(geom="text", x=3, y=2.9, label="**",size=6,color="black")+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size=12),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 12,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 12),
        legend.title = element_text(face = 'bold'),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        legend.key = element_blank(),
        legend.direction =  "horizontal",legend.position = c(0.5,0.9))
LUI.sep

#ggsave(LUI.sep,filename = '/xx/all_LUI.sep.tiff',compression='lzw', width = 8,height = 4,dpi=200)
```
#4 fig2b-g 
#4.1 all taxa
```{r}
#1import the data
db<-read.csv(file = '/xx/data.csv',sep=";",stringsAsFactors=T)
#2set the factor levels
levels(as.factor(db$LU))
db$LU<-factor(db$LU,c("Urban","SV","Plantation","Pasture","Cropland","Primary"))
#3 Alien presence/absence for logistical model. 
db$Alien.presence <- as.logical(db$alien_freq)
#4run the models
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1)
#5check overdispersion
simulateResiduals(m , use.u = T) %>% testDispersion() # looks good
#6 checkt random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB

#try the pairwise comparison 
pred.full<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#get the odds ratios to primary
pred.full_2<-pred.full[grepl("Primary",pred.full$contrast),]
pred.full_2$contrast<-as.character(pred.full_2$contrast)
#add the reference
pred.full_2[6,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)
library(stringr)
pred.full_2[c('name1', 'name2')] <- str_split_fixed(pred.full_2$contrast, '/', 2)
names(pred.full_2)
names(pred.full_2)[10]<-c("LU")
pred.full_2$LU<-as.factor(pred.full_2$LU)
levels(pred.full_2$LU)<-c("Cropland","Pasture","Plantation",
                          "Primary","Secondary", "Urban")
pred.full_2$LU<-
  factor(pred.full_2$LU,c("Primary","Secondary","Plantation",
                          "Pasture","Cropland","Urban"))
names(pred.full_2)[2]<-c("Odds")
pred.full_2$Odds<-as.numeric(pred.full_2$Odds)
pred.full_2$SE<-as.numeric(pred.full_2$SE)
pred.full_2$LU<-as.factor(pred.full_2$LU)
```
#4.1.1 make fig.2b
```{r}
all.LU<-ggplot(pred.full_2 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Odds ratio of alien occurrence",
                     limits=c(0,30),breaks=seq(0,30,10))+
  geom_point(position = position_dodge(width=.6),size=3)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary V.','Secondary V.','Plantation',
                             'Pasture','Cropland','Urban'))+
  
  annotate(geom="text", x=2, y=5, label="***",size=6,color="#4393C3")+
  annotate(geom="text", x=3, y=8.5, label="***",size=6,color="#92C5DE")+
  annotate(geom="text", x=4, y=7.5, label="***",size=6,color="#F4A582")+
  annotate(geom="text", x=5, y=11.5, label="***",size=6,color="red")+
  annotate(geom="text", x=6, y=15, label="***",size=6,color="#B2182B")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
all.LU
#ggsave(all.LU,filename = '/xx/fig2.b.tiff',compression='lzw',width =3,height = 2.5,dpi=200)
```
#4.2 ants
```{r}
#get the ants group
db.t<-db[db$taxa=="Ants",]
dplyr::count(db.t,LU,Alien.presence)
#run the model
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db.t , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),nAGQ = 1)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # good
# check random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB

ant<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
ant.1<-ant[grepl("Primary",ant$contrast),]
ant.1$contrast<-as.character(ant.1$contrast)
ant.1[6,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)

ant.1[c('name1', 'name2')] <- str_split_fixed(ant.1$contrast, '/', 2)
names(ant.1)
names(ant.1)[10]<-c("LU")
ant.1$LU<-as.factor(ant.1$LU)
levels(ant.1$LU)<-c("Cropland","Pasture","Plantation","Primary","Secondary","Urban")
ant.1$LU<-
  factor(ant.1$LU,c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(ant.1)[2]<-c("Odds")
ant.1$Odds<-as.numeric(ant.1$Odds)
ant.1$SE<-as.numeric(ant.1$SE)
#write.table(ant.1,file = '/Users/daijunliu/Downloads/ant.LU.odds.csv',row.names = F,sep = ';')
```
#4-2-1 fig.2c
```{r}
ant.all<-ggplot(ant.1 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien incidence",
                     limits=c(-1,65),breaks=seq(0,60,20))+
  geom_point(position = position_dodge(width=.6),size=3)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  annotate(geom="text", x=3, y=64, label="***",size=6,color="#92C5DE")+
  annotate(geom="text", x=4, y=20, label="*",size=6,color="#F4A582")+
  annotate(geom="text", x=5, y=34, label="*",size=6,color="red")+
  
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
ant.all
#ggsave(ant.all,filename = '/xx/ant.all.tiff',compression='lzw',width =3,height = 2.5,dpi=200)
```
#4.3 birds
```{r}
#subset the birds
db.t<-db[db$taxa=="Birds",]
#run the models
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db.t , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # slightly overdispersed, but seems OK enough!
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # KEEP SS/SSB
#use the parewise comparison
Bird<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#select the odds ratios compared to reference
Bird.1<-Bird[grepl("Primary",Bird$contrast),]
Bird.1$contrast<-as.character(Bird.1$contrast)
#set the reference
Bird.1[6,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)
Bird.1[c('name1', 'name2')] <- str_split_fixed(Bird.1$contrast, '/', 2)
names(Bird.1)
names(Bird.1)[10]<-c("LU")
#set the factor
Bird.1$LU<-as.factor(Bird.1$LU)
levels(Bird.1$LU)<-c("Cropland","Pasture","Plantation","Primary","Secondary", "Urban")
Bird.1$LU<-
  factor(Bird.1$LU,c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(Bird.1)[2]<-c("Odds")
Bird.1$Odds<-as.numeric(Bird.1$Odds)
Bird.1$SE<-as.numeric(Bird.1$SE)
```
#4.3.1 fig.2d
```{r}
Bird.all<-ggplot(Bird.1 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien incidence",
                     limits=c(0,30),breaks=seq(0,30,10))+
   geom_point(position = position_dodge(width=.6),size=3)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  annotate(geom="text", x=3, y=9, label="***",size=6,color="#92C5DE")+
  annotate(geom="text", x=5, y=18, label="***",size=6,color="red")+
  annotate(geom="text", x=6, y=26, label="***",size=6,color="#B2182B")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
Bird.all
#ggsave(Bird.all,filename = '/xx/Bird.all.tiff',compression='lzw',width =3,height = 2.5,dpi=200)
```
#4.4 mamals
```{r}
#subset the mammals group
db.t<-db[db$taxa=="Mammals",]
#delete the urban and cropland due to low number of assemblages
db.t<-subset(db.t,!(LU %in% "Urban" & taxa %in%"Mammals"))
db.t<-subset(db.t,!(LU %in% "Cropland" & taxa %in%"Mammals"))
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db.t , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # slightly overdispersed, but seems OK enough!
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB

#get the parewise
mam<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#get the odd ratios compare to primary
mam.1<-mam[grepl("Primary",mam$contrast),]
mam.1$contrast<-as.character(mam.1$contrast)
#set the reference level and missing lu-types
mam.1[4,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)
mam.1[5,]<-c("Cropland",NA,NA, NA,NA,NA,NA,NA,NA)
mam.1[6,]<-c("Urban",NA,NA, NA,NA,NA,NA,NA,NA)
mam.1[c('name1', 'name2')] <- str_split_fixed(mam.1$contrast, '/', 2)
names(mam.1)
names(mam.1)[10]<-c("LU")
#set teh factor for LU
mam.1$LU<-as.factor(mam.1$LU)
levels(mam.1$LU)<-c("Cropland","Pasture","Plantation","Primary","Secondary","Urban")
mam.1$LU<-
  factor(mam.1$LU,c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(mam.1)[2]<-c("Odds")
mam.1$Odds<-as.numeric(mam.1$Odds)
mam.1$SE<-as.numeric(mam.1$SE)

```
#4.4.1 fig.2e
```{r}
mam.all<-ggplot(mam.1 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien incidence",
                     limits=c(0,30),breaks=seq(0,30,10))+
  geom_point(position = position_dodge(width=.6),size=3)+
   scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  annotate(geom="text", x=2, y=11, label="***",size=6,color="#4393C3")+
  annotate(geom="text", x=3, y=6.5, label="*",size=6,color="#92C5DE")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
mam.all
#ggsave(mam.all,filename = '/xx/mam.all.tiff',compression='lzw',width =3,height = 2.5,dpi=200)
```
#4.5 spider
```{r}
#subset the spider data
db.t<-db[db$taxa=="Spiders",]
#delete the plantation and urban due to low samples
db.t<-subset(db.t,!(LU %in% "Plantation" & taxa %in%"Spiders"))
db.t<-subset(db.t,!(LU %in% "Urban" & taxa %in%"Spiders"))
dplyr::count(db.t,LU,Alien.presence)
#run the statistical models
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db.t , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),nAGQ = 1)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # slightly overdispersed, but seems OK
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) # keep SS/SSB
#get the parewise
spider<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#select the odds ratios compare to primary
spider.1<-spider[grepl("Primary",spider$contrast),]
spider.1$contrast<-as.character(spider.1$contrast)
#set the reference and add the missing lu types
spider.1[4,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)
spider.1[5,]<-c("Plantation",NA,NA, NA,NA,NA,NA,NA,NA)
spider.1[6,]<-c("Urban",NA,NA, NA,NA,NA,NA,NA,NA)
spider.1[c('name1', 'name2')] <- str_split_fixed(spider.1$contrast, '/', 2)
names(spider.1)
names(spider.1)[10]<-c("LU")
#change to factor
spider.1$LU<-as.factor(spider.1$LU)
levels(spider.1$LU)<-c("Cropland","Pasture","Plantation","Primary","Secondary","Urban")
spider.1$LU<-
  factor(spider.1$LU,c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(spider.1)[2]<-c("Odds")
spider.1$Odds<-as.numeric(spider.1$Odds)
spider.1$SE<-as.numeric(spider.1$SE)
spider.1$LU<-as.factor(spider.1$LU)
```
#4.5.1 fig.2f
```{r}
spider.all<-ggplot(spider.1 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Alien incidence",
                     limits=c(0,320),breaks=seq(0,300,100))+
   geom_point(position = position_dodge(width=.6),size=3)+
   scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plantation',
                             'Pasture','Cropland','Urban'))+
  annotate(geom="text", x=4, y=310, label="***",size=6,color="#F4A582")+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
spider.all
#ggsave(spider.all,filename = '/xx/spider.all.tiff',compression='lzw',width =3,height = 2.5,dpi=200)

```
#4.6 vascular plants
```{r}
db.t<-db[db$taxa=="Vascular plants",]
#delete the assemblages under urban areas due to low samples
db.t<-subset(db.t,!(LU %in% "Urban" & taxa %in%"Vascular plants"))
dplyr::count(db.t,LU,Alien.presence)
levels(db.t$LU)
m <- glmer(Alien.presence ~ LU + (1|SS/SSB) , 
          data = db.t , family = binomial , 
          control = glmerControl(optimizer = "bobyqa" , 
                                 optCtrl = list(maxfun = 1e5)),
           nAGQ = 1)
summary(m)
# check overdispersion with DHARMa package to decide if OLRE is needed. Simulate residuals conditional on random effects. 
simulateResiduals(m , use.u = T) %>% testDispersion() # ok
# select random effects structure
m2 <- update(m , . ~ . -(1|SS/SSB) + (1|SS))
anova(m , m2) #keep SS/SSB
#get the parewise
plant<-m %>% emmeans(specs = ~LU , type = "response") %>%pairs(infer = T , adjust = "tukey")%>%as.data.frame()
#get the odds ratios to primary
plant.1<-plant[grepl("Primary",plant$contrast),]
plant.1$contrast<-as.character(plant.1$contrast)
#set the reference and add the level for missing urban
plant.1[5,]<-c("Primary / Primary",1,NA, NA,NA,NA,NA,NA,NA)
plant.1[6,]<-c("Urban",NA,NA, NA,NA,NA,NA,NA,NA)
plant.1[c('name1', 'name2')] <- str_split_fixed(plant.1$contrast, '/', 2)
names(plant.1)
names(plant.1)[10]<-c("LU")
#change factor
plant.1$LU<-as.factor(plant.1$LU)
levels(plant.1$LU)<-c("Cropland","Pasture","Plantation","Primary","Secondary", "Urban")
plant.1$LU<-
  factor(plant.1$LU,c("Primary","Secondary","Plantation","Pasture","Cropland","Urban"))
names(plant.1)[2]<-c("Odds")
```
#4.6.1 fig.2g
```{r}
plant.1$Odds<-as.numeric(plant.1$Odds)
plant.1$SE<-as.numeric(plant.1$SE)
plant.all<-ggplot(plant.1 , aes(LU , Odds,color=LU))+
  geom_errorbar(aes(ymin = Odds-SE , ymax = Odds+SE) ,width=0.4, 
                position = position_dodge(width=.6))+
  scale_y_continuous(name="Odds ratio of alien incidence",
                     limits=c(0,30),breaks=seq(0,30,10))+
  geom_point(position = position_dodge(width=.6),size=3)+
  scale_color_manual(name='LU-types',
                     values = c("#2166AC","#4393C3","#92C5DE",
                                "#F4A582","red","#B2182B"),
                     label=c('Primary','Secondary','Plplantation',
                             'Pasture','Cropland','Urban'))+
  guides(colour = guide_legend(nrow = 1),shape=guide_legend(nrow = 1))+
  annotate(geom="text", x=2, y=4, label="**",size=6,color="#4393C3")+
  annotate(geom="text", x=3, y=17.5, label="***",size=6,color="#92C5DE")+
  annotate(geom="text", x=4, y=5, label="**",size=6,color="#F4A582")+
  annotate(geom="text", x=5, y=5, label="***",size=6,color="red")+
  theme_bw()+
  theme(panel.grid.major.x = element_blank() , 
        axis.ticks.length=unit(0.08,"inch"),
        panel.grid.major.y = element_line(size = 0.6 , colour = "grey90") ,
        panel.spacing = unit(0,"lines") , 
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.x = element_text(colour = "black",angle = 25, 
                                   size = 10,vjust = 0.6) ,
        axis.text.y = element_text(colour = "black",  size = 10),
        legend.position = "none")
plant.all
#ggsave(plant.all,filename = '/xx/plant.all.tiff',compression='lzw',width =3,height = 2.5,dpi=200)

```
